### ISSUE TITLE
When i inject the cheat without my game closing!

### ISSUE THREAD

**Issue by ALEHACKsp** [HowYouDoinMate/GrandTheftAutoV-Cheat#1]
Well first congratulations for the project,
I'm trying to inject it but my game is crashing,
I would like to know how I can use the cheat without my game closing, I am using injector GH, I use it in EPIC GAMES,

**Comment by HowYouDoinMate** [comment]
Earlier this year I unfortunately had to remove this project. I restored it a few days ago.

The latest release is not yet updated for the game's march patch, I have not looked too much into what changed.

**Comment by HowYouDoinMate** [comment]
This issue has been resolved with the release of v1.3.0.5
https://github.com/HowYouDoinMate/GrandTheftAutoV-Cheat/releases/tag/v1.3.0.5

**Comment by ALEHACKsp** [comment]
Congratulations Cheat is great, can I update it to a new version? The only thing I understand about gtav is that I should update Crossmaping correct, correct me if I'm wrong? I keep your sources since I met your Github I kept it I have a HD with your projects, I wanted to know how do I update that cheat of RDR2? do you have Discord?
