### ISSUE TITLE
Textures.ytd

### ISSUE THREAD

**Issue by KottenFAC** [HowYouDoinMate/GrandTheftAutoV-Cheat#2]
so when i open Textures.ytd and try to replace "HeaderDefaultTransparent" and inject its still the same header since before and the "HeaderDefaultTransparent" i changed have changed back to same as before, i cant find in the code where it gets its data from.

**Comment by vungsung** [comment]
I think it's from the project resource (`GTA.rc` under the Solution Explorer), and the resource data was imported from `Textures.ytd` which is in the root directory of this project.

**Comment by HowYouDoinMate** [comment]
Whenever you inject the DLL it overwrites any existing Textures.ytd inside the directory, so instead of replacing it on disk, replace it in the source directory and recompile.

**Comment by HowYouDoinMate** [comment]
Or comment the code in DllMain that extracts the file to disk ^

**Comment by KottenFAC** [comment]
Oh ok will check at it when i get home, thx for the help.

**Comment by KottenFAC** [comment]
got it working, i understand how it works now so thx for the help,
