### ISSUE TITLE
what a about source RDR2 cheat ?

### ISSUE THREAD

**Issue by ALEHACKsp** [HowYouDoinMate/GrandTheftAutoV-Cheat#2]
Congratulations Cheat is great, can I update it to a new version? The only thing I understand about gtav is that I should update Crossmaping correctly, correct me if I'm wrong? I keep your sources since I met your Github I kept it I have an HD with your projects, I wanted to know how do I update that cheat of RDR2? do you have Discord?

**Comment by HowYouDoinMate** [comment]
The latest release for the GTAV cheat in this repository is fully updated for the latest game update.

For RDR2, I won't be working on that cheat any more; cross table definitely needs to be updated. I won't provide any further support past this.
