### ISSUE TITLE
1.51 global fix

### ISSUE THREAD

**Issue by vungsung** [HowYouDoinMate/GrandTheftAutoV-Cheat#3]
updated ra$nk, ca$sh, earn$ings for 1.51

aW50IHJhbmsgPSBnbG9iYWxIYW5kbGUoMTU5MDUzNSkuQXQocCwgODc2KS5BdCgyMTEpLkF0KDYpLkFzPGludD4oKTsKaW50IGVhcm5pbmdzID0gZ2xvYmFsSGFuZGxlKDE1OTA1MzUpLkF0KHAsIDg3NikuQXQoMjExKS5BdCg1NikuQXM8aW50PigpOwppbnQgY2FzaCA9IGdsb2JhbEhhbmRsZSgxNTkwNTM1KS5BdChwLCA4NzYpLkF0KDIxMSkuQXQoMykuQXM8aW50PigpOwppbnQgYmFua01vbmV5ID0gZWFybmluZ3MgLSBjYXNoOw==

https://github.com/HowYouDoinMate/GrandTheftAutoV-Cheat/blob/8bbe9dd09b35e03dfed53a6f43bab9fadd02d8f8/Source/GameFunctions.cpp#L641

**Comment by HowYouDoinMate** [comment]
Perform a Pull request for the change, I will have a look and push it to Master than.
