### ISSUE TITLE
Game crashes: Failed to load textures

### ISSUE THREAD

**Issue by gamerover98** [HowYouDoinMate/GrandTheftAutoV-Cheat#6]
Hi, I've compiled your source code with Visual Studio and then I've injected the output dll file into the game with "Extreme Injector" program. 

After joining into the game, it freezes and a Minimap Notification says me "Failed to load Texture".
How can I load the Textures.ytd file?

Thanks

**Comment by gamerover98** [comment]
I solved this issue by placing the Textures file into the  %MY_USER%\AppData\Local\Temp\gtav folder!
Ok, but how can I do it without placing it manually?

**Comment by HowYouDoinMate** [comment]
When injecting, the texture file is written to the current directory of the cheat module (GTAV.dll, by default). It is important to **NOT** use Manual Map injection techniques (and other erase features) as they prevent WinAPI functions like 'GetModuleFileNameA()' from working.

**Comment by gamerover98** [comment]
So, I have to use another injection program?
With the current injection (with silent injection enabled into the config) your dll works but I could be banned?

**Comment by HowYouDoinMate** [comment]
Extreme Injector's default setting injects using `LoadLibraryA()`, which is the preferred method with the reason mentioned in my previous comment. You can also use the SMI project, which you can find [here](https://github.com/HowYouDoinMate/SimpleModuleInjector) which uses the same (LoadLibraryA) classic injection method.

"but I could be banned?
Yes, in theory. But you should be fine.
